# base image for build custom image 
FROM redhat/ubi9:latest

# USE RUN Instructio install package
RUN yum install httpd -y 

# COPY Content in 
COPY src/index.html /var/www/html/

# start httpd service
RUN echo "/usr/sbin/httpd -k start &> /dev/null" >> /root/.bashrc

# EXPOSE use port 
EXPOSE 80
