apiVersion: v1
kind: Pod
metadata:
  name: multicontainerapp
  labels:
    app: multicontainerapp
spec:
  containers:
  - name: multicontainerapp
    image: python:3.8-slim
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
        name: flask
  - name: redis
    image: redis:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 6379
        name: redis    

---
apiVersion: v1
kind: Service
metadata:
  name: multiapp-svc
spec:
  selector:
    app: multicontainerapp
  type: NodePort    
  ports:
  - port: 5000
    targetPort: 5000
    name: flask
  - port: 6379
    targetPort: 6379  
    name: redis
