# git repo ebs : https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md
# kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-1.61"
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp2
  encrypted: "true"
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-store-pod
  labels:
    app.kubernetes.io/name: ebs-store-pod
spec:
  volumes:
  - name: ebs-store-pod
    persistentVolumeClaim: 
      claimName: ebs-store-pod
  containers:
  - name: ebs-store-pod
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: ebs-store-pod
      mountPath: /opt
      