apiVersion: v1
kind: Namespace
metadata:
  name: autotest

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs-csi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  containers:
  - name: myapp
    image: ubuntu:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: data-mount
      mountPath: /opt
    command:
      - sleep
      - "3600"
  volumes:
  - name: data-mount
    persistentVolumeClaim:
      claimName: mypvc  
    