apiVersion: v1
kind: Secret
metadata:
  name: intial-admin-password
  namespace: database 
  label: 
    app: mysql
type: Opaque
data:
  password: U3Ryb25ncGFzc3tAMTIzfQ==    


---
apiVersion: v1
kind: Secret
metadata:
  name: user-access-secret
  namespace: database
  label: 
    app: mysql
type: Opaque
data:
  password: ZGJ1c2VyQDEyMw==
  user: ZGJ1c2Vy

