# Base Image
FROM pyapp:alpine

# set working path
WORKDIR /app

COPY app/requirements.txt .

RUN apk add --no-cache gcc musl-dev linux-headers python3-dev

# Create virtual environment
RUN python3 -m venv /venv

# Activate venv path
ENV PATH="/venv/bin:$PATH"

RUN pip install --no-cache-dir -r requirements.txt

COPY app/  .
 
CMD ["python","app.py"]

EXPOSE 5000
