# echo -n UmVkaGF0MTIzNDU2 | base64 -d 
# echo -n cmVkaGF0MTIzNDU2 | base64 -d
# echo -n YWRtaW5AZXhhbXBsZS5jb20= | base64 -d
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres
type: Opaque
data:
  password: UmVkaGF0MTIzNDU2

---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: postgres
type: Opaque
data:
  password: cmVkaGF0MTIzNDU2
  user: YWRtaW5AZXhhbXBsZS5jb20=