apiVersion: v1
kind: Namespace
metadata:
  name: mongo

---
apiVersion: v1
kind: Secret
metadata:
  name: mogo-admin-secret
  namespace: mongo
type: Opaque
data:
  password: bXlzcWwtcGFzcw==
  user:  bXlzcWwtdXNlcg== 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: mongo
  labels: 
    app: mongoapp
spec:
  selector:
    matchLabels:
      app: mongoapp
  template:
    metadata:
      labels:
        app: mongoapp
    spec:
      containers:
      - name: mongoapp
        image: mongo:7.0.34-jammy
        resources:
          requests:
            memory: "300Mi"
            cpu: "500m"
          limits:
            memory: "400Mi"
            cpu: "800m"  
        ports:
        - containerPort: 27017
          name: mongoport  
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mogo-admin-secret
              key: user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:    
            secretKeyRef:
              name: mogo-admin-secret
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongo 
spec:
  selector:
    app: mongoapp
  ports:
  - port: 27017
    targetPort: 27017
    name: mongoport
