apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: mongo
spec:
  selector:
    matchLabels:
      app: mongo-client
  template:
    metadata:
      labels:
        app: mongo-client
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        env:
        - name: ME_CONFIG_BASICAUTH_ENABLED
          value: "true"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: mongoexpressuser 
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: mongoexpresspass  
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://mysql-user:mysql-pass@mongo-svc:27017/"
        - name: ME_CONFIG_MONGODB_PORT
          value: "27017"
        - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
          value: "true"
        resources:
          limits:
            memory: "500Mi"
            cpu: "700m"
        ports:
        - containerPort: 8081
          name: mongo-exs-port

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-exp-svc
  namespace: mongo
spec:
  selector:
    app: mongo-client
  ports:
  - port: 8081
    targetPort: 8081
  type: NodePort
